/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Document, Operation } from "document-viz-wasm";
export { Document, Operation } from "document-viz-wasm";
export namespace Components {
    interface NamaGraphViz {
        "peer"?: string;
    }
    interface NamaLogViz {
        "peer"?: string;
    }
    interface NamaPeer {
        "author": string;
        "interval": number;
        "latency": number;
        "namaDoc"?: Document;
    }
    interface NamaPeerControls {
        "frequency": number;
        "latency": number;
        "online": boolean;
        "setFrequency": CallableFunction;
        "setLatency": CallableFunction;
        "setOnline": CallableFunction;
    }
}
export interface NamaPeerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNamaPeerElement;
}
declare global {
    interface HTMLNamaGraphVizElement extends Components.NamaGraphViz, HTMLStencilElement {
    }
    var HTMLNamaGraphVizElement: {
        prototype: HTMLNamaGraphVizElement;
        new (): HTMLNamaGraphVizElement;
    };
    interface HTMLNamaLogVizElement extends Components.NamaLogViz, HTMLStencilElement {
    }
    var HTMLNamaLogVizElement: {
        prototype: HTMLNamaLogVizElement;
        new (): HTMLNamaLogVizElement;
    };
    interface HTMLNamaPeerElementEventMap {
        "namaSend": { peer: string; latency: number; operations: Operation[] };
        "namaChange": { peer: string; operations: Operation[]; pruned: string[] };
    }
    interface HTMLNamaPeerElement extends Components.NamaPeer, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNamaPeerElementEventMap>(type: K, listener: (this: HTMLNamaPeerElement, ev: NamaPeerCustomEvent<HTMLNamaPeerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNamaPeerElementEventMap>(type: K, listener: (this: HTMLNamaPeerElement, ev: NamaPeerCustomEvent<HTMLNamaPeerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNamaPeerElement: {
        prototype: HTMLNamaPeerElement;
        new (): HTMLNamaPeerElement;
    };
    interface HTMLNamaPeerControlsElement extends Components.NamaPeerControls, HTMLStencilElement {
    }
    var HTMLNamaPeerControlsElement: {
        prototype: HTMLNamaPeerControlsElement;
        new (): HTMLNamaPeerControlsElement;
    };
    interface HTMLElementTagNameMap {
        "nama-graph-viz": HTMLNamaGraphVizElement;
        "nama-log-viz": HTMLNamaLogVizElement;
        "nama-peer": HTMLNamaPeerElement;
        "nama-peer-controls": HTMLNamaPeerControlsElement;
    }
}
declare namespace LocalJSX {
    interface NamaGraphViz {
        "peer"?: string;
    }
    interface NamaLogViz {
        "peer"?: string;
    }
    interface NamaPeer {
        "author"?: string;
        "interval"?: number;
        "latency"?: number;
        "namaDoc"?: Document;
        "onNamaChange"?: (event: NamaPeerCustomEvent<{ peer: string; operations: Operation[]; pruned: string[] }>) => void;
        "onNamaSend"?: (event: NamaPeerCustomEvent<{ peer: string; latency: number; operations: Operation[] }>) => void;
    }
    interface NamaPeerControls {
        "frequency"?: number;
        "latency"?: number;
        "online"?: boolean;
        "setFrequency"?: CallableFunction;
        "setLatency"?: CallableFunction;
        "setOnline"?: CallableFunction;
    }
    interface IntrinsicElements {
        "nama-graph-viz": NamaGraphViz;
        "nama-log-viz": NamaLogViz;
        "nama-peer": NamaPeer;
        "nama-peer-controls": NamaPeerControls;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nama-graph-viz": LocalJSX.NamaGraphViz & JSXBase.HTMLAttributes<HTMLNamaGraphVizElement>;
            "nama-log-viz": LocalJSX.NamaLogViz & JSXBase.HTMLAttributes<HTMLNamaLogVizElement>;
            "nama-peer": LocalJSX.NamaPeer & JSXBase.HTMLAttributes<HTMLNamaPeerElement>;
            "nama-peer-controls": LocalJSX.NamaPeerControls & JSXBase.HTMLAttributes<HTMLNamaPeerControlsElement>;
        }
    }
}
