/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NamaLogViz {
        "addNode": (id: string, seqNum: number, previous?: string) => Promise<void>;
        /**
          * The log authors name
         */
        "author": string;
        "layout": () => Promise<void>;
        "prune": (id: string) => Promise<void>;
    }
}
declare global {
    interface HTMLNamaLogVizElement extends Components.NamaLogViz, HTMLStencilElement {
    }
    var HTMLNamaLogVizElement: {
        prototype: HTMLNamaLogVizElement;
        new (): HTMLNamaLogVizElement;
    };
    interface HTMLElementTagNameMap {
        "nama-log-viz": HTMLNamaLogVizElement;
    }
}
declare namespace LocalJSX {
    interface NamaLogViz {
        /**
          * The log authors name
         */
        "author"?: string;
    }
    interface IntrinsicElements {
        "nama-log-viz": NamaLogViz;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nama-log-viz": LocalJSX.NamaLogViz & JSXBase.HTMLAttributes<HTMLNamaLogVizElement>;
        }
    }
}
